version: "3.8"

services:

  traefik:
    image: "traefik:2.5"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--entrypoints.http.address=:80"
      - "--log.level=INFO"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker=true"

  artists:
    image: "node:16.7-alpine"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.artists.rule=Host(`artists.localhost`)"
      - "traefik.http.services.artists.loadbalancer.server.port=3000"
    volumes:
      - "./services/artists:/app"
    environment:
      PORT: "3000"
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: "/app"
    command: "npm run dev"
